#!/bin/bash
set -eux

preferredEngine='config-get engine'
oppositeEngine=''

if [ $preferredEngine == "nginx" ]; then # If engine is nginx
	/etc/init.d/apache2 stop

	apt-get remove -y apache2 php5-cgi curl libapache2-mod-php5 php5-cli
	apt-get install -y nginx php5 php5-fpm
else #If engine is apache(2)
	/etc/init.d/nginx stop

	apt-get remove -y nginx php5 php5-fpm
	apt-get install -y apache2 php5-cgi curl libapache2-mod-php5 php5-cli
fi

/etc/init.d/$preferredEngine start
