#!/bin/bash
set -e

preferredEngine=$(config-get engine)

echo "It's like Metis is a really awesome car and you're swapping out the engine for a better one."

if [ "$preferredEngine" == "nginx" ]; then # If engine is nginx
	apt-get remove -y php5-cgi curl libapache2-mod-php5
	apt-get install -y nginx php5 php5-fpm
	service nginx start
else #If engine is apache(2)
	apt-get remove -y nginx php5 php5-fpm
	apt-get install -y php5-cgi curl libapache2-mod-php5
	service apache2 start
fi
