#!/bin/bash
set -e

preferredEngine=$(config-get engine)

if [ "$preferredEngine" == "nginx" ]; then # If engine is nginx
	apt-get remove -y apache2 php5-cgi curl libapache2-mod-php5 php5-cli
	apt-get install -y nginx php5 php5-fpm
	service nginx start
else #If engine is apache(2)
	apt-get remove -y nginx php5 php5-fpm
	apt-get install -y apache2 php5-cgi curl libapache2-mod-php5 php5-cli
	service apache2 start
fi
