#!/bin/bash
set -e

preferredEngine=$(config-get engine)

echo "It's like Metis is a really awesome car and you're swapping out the engine for a better one."

if [ "$preferredEngine" == "nginx" ]; then # If engine is nginx
        if [ $(dpkg --get-selections apache2 2>&1 | grep -c 'install') -eq 1 ]; then # If apache2 $
                service apache2 stop
                apt-get remove -y apache2 php5-cgi curl libapache2-mod-php5
        fi

        apt-get install -y nginx php5 php5-fpm
        service nginx start
else #If engine is apache(2)
        if [ $(dpkg --get-selections nginx 2>&1 | grep -c 'install') -eq 1 ]; then # If nginx is i$
                service nginx stop
                apt-get remove -y nginx php5 php5-fpm
        fi

        apt-get install -y apache2 php5-cgi curl libapache2-mod-php5
        service apache2 start
fi

