#!/bin/bash
set -e # If any command fails, stop execution.

installMetis(){ #Function to pull and install Metis
	# Clone the git repository
	echo "Cloning Metis git repository (stable branch). No worries, it is a perfect clone."
	mkdir -p /tmp/metis # Create a temporary directory to work in
	git clone --branch master git@github.com:StroblIndustries/Metis.git /tmp/metis # Clone the repo to /tmp/metis

	cd /tmp/metis/

	unnecessaryContent=('builders' 'juju-charm' 'php' 'typescript' 'stable.zip') # Array of unnecessary content from the git repo.

	echo "We're removing some unnecessary stuff. It's like unstuffing a teddy bear."

	for content in ${unnecessaryContent[@]} # Recurse over array
	do
		rm -rf "$content" # Remove the individual item(s)
	done

	echo "The shipping trucks have arrived and are moving Metis to it's appropriate spot in the world."

	mkdir -p /var/www/Metis # Make sure the /var/www/Metis directory exists
	mv /tmp/metis/* /var/www/Metis/ # Move the contents of temp to Metis
	chmod -R 1777 /var/www/ # Force 777 permissions
}

apt-get install -y git # Ensure necessary git dependency exist.

# Check for existing installs
echo "Our detectives are on the case. Checking for an existing Metis install."

if [ -f /var/www/Metis/metis.php ]; then #If Metis is already installed
	echo "Our hunch was right. Found an existing Metis install. Updating now."

	cp /var/www/Metis/nodeList.json /tmp/ # Copy nodeList.json
	cp -r /var/www/Metis/data /tmp/ # Copy over existing data
	rm -r /var/www/Metis # Uninstall Metis

	installMetis # Reinstall Metis

	# Re-install any old data
	echo "Copying over old Metis config and data. We're doing some serious magic over here."
	mv -f /tmp/nodeList.json /var/www/Metis/ # Copy over old nodeList.json
	mv -fr /tmp/data /var/www/Metis # Copy over Metis data folder

	echo "Metis is done updating \o/ Mission accomplished."
else #If Metis is NOT already installed
	echo "Found no Metis install. The construction crew has arrived and we're installing Metis now."

	# Dependency Checking (No sense in re-installing dependencies)

	echo "Doing some dependency checking. We like things to work."

	preferredEngine=$(config-get engine)

	if [ "$preferredEngine" == "nginx" ]; then # If engine is nginx
		apt-get install -y nginx php5 php5-fpm php5-curl
	elif [ "$preferredEngine" == "apache2" ]; then #If engine is apache(2)
		apt-get install -y php5-cgi curl libapache2-mod-php5 php5-curl
	fi

	# End of Dependency Checking

	installMetis #Install Metis (fresh install)

	echo "Metis is done installing \o/ We're cheering like schoolgirls over here."
fi