#!/bin/bash
set -e

preferredEngine=$(config-get engine)

if [ "$preferredEngine" == "nginx" ]; then # If engine is nginx
	service nginx start
else #If engine is apache(2)
	service apache2 start
fi

echo "Awww yea. Let's get to work! Service $preferredEngine is up and running."